import { useEffect, useState } from "react";
import { Activity, AlertTriangle, Bell, FolderKanban, LayoutDashboard, BarChart3, BrainCircuit, LogOut, Menu } from "lucide-react";
import { Link } from "react-router-dom";
import { api } from "../api/client";
import StatCard from "../components/StatCard";
import "./Dashboard.css";

function Dashboard() {
  const [summary, setSummary] = useState(null);
  const [projects, setProjects] = useState([]);
  const [error, setError] = useState("");
  useEffect(() => { Promise.all([api.getDashboardSummary(), api.getProjects(3)]).then(([summaryData, projectData]) => { setSummary(summaryData); setProjects(projectData.items || []); }).catch((requestError) => setError(requestError.message)); }, []);
  return <div className="dashboard-container"><aside className="sidebar"><div className="sidebar-logo"><div className="logo-eye">👁</div><div><h2>MARG</h2><span>Project Intelligence</span></div></div><nav className="sidebar-nav"><Link to="/dashboard" className="nav-item active"><LayoutDashboard size={20} /><span>Dashboard</span></Link><Link to="/projects" className="nav-item"><FolderKanban size={20} /><span>Projects</span></Link><Link to="/predictions" className="nav-item"><BrainCircuit size={20} /><span>Predictions</span></Link><Link to="/alerts" className="nav-item"><Bell size={20} /><span>Alerts</span></Link><Link to="/analytics" className="nav-item"><BarChart3 size={20} /><span>Analytics</span></Link></nav><div className="sidebar-bottom"><div className="user-box"><div className="user-avatar">U</div><div><strong>User</strong><span>Government Authority</span></div></div><Link to="/" className="logout-btn"><LogOut size={18} />Logout</Link></div></aside><main className="dashboard-main"><header className="dashboard-header"><div><div className="mobile-menu"><Menu /></div><p className="welcome-text">MARG PROJECT INTELLIGENCE</p><h1>Project Monitoring Dashboard</h1><p className="header-description">Live counts and anomaly indicators from MongoDB.</p></div></header>{error && <p role="alert">Unable to load dashboard: {error}</p>}{!summary && !error && <p>Loading dashboard...</p>}{summary && <><section className="stats-grid"><StatCard icon={FolderKanban} color="blue" label="Total Projects" value={summary.total_projects.toLocaleString()} description="Stored projects" /><StatCard icon={Activity} color="green" label="Total Snapshots" value={summary.total_snapshots.toLocaleString()} description="Stored snapshots" /><StatCard icon={AlertTriangle} color="orange" label="Latest Anomalies" value={summary.projects_with_latest_anomaly.toLocaleString()} description="Projects with latest anomaly flags" /><StatCard icon={Bell} color="red" label="Risk Distribution" value="Unavailable" description="Not persisted; no portfolio inference" /></section><section className="dashboard-card projects-card"><div className="card-header"><div><h3>Recent projects</h3><p>Projects returned by the backend</p></div><Link to="/projects">View all projects →</Link></div><div className="project-table"><div className="table-header"><span>Project</span><span>Identifier</span><span>Metadata</span></div>{projects.map((project) => <div className="project-row" key={project.project_id}><div className="project-name"><div className="project-icon"><FolderKanban size={18} /></div><div><strong>{project.project_name || project.project_id}</strong><span>{project.sector || "Sector unavailable"}</span></div></div><span>{project.project_id}</span><span>{project.project_code || "Project code unavailable"}</span></div>)}</div></section></>}</main></div>;
}

export default Dashboard;
